[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 1

[[main]]
  identifier = "posts"
  name = "posts"
  url = "posts"
  weight = 2

[[main]]
  identifier = "tags"
  name = "tags"
  url = "tags"
  weight = 3

[[main]]
  identifier = "categories"
  name = "categories"
  url = "categories"
  weight = 3